version: '3'
services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./provision/nginx/conf:/etc/nginx/
      - ./provision/certs:/certificates
      - ./.state/nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nexus
  nexus:
    image: sonatype/nexus3:3.21.1
    volumes:
      - ./.state/nexus/data:/nexus-data
    ports:
      - 8081:8081
      - 8082:8082
